/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gltest_GLInterface */

#ifndef _Included_com_example_gltest_GLInterface
#define _Included_com_example_gltest_GLInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gltest_GLInterface
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_gltest_GLInterface_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_gltest_GLInterface_render
  (JNIEnv *, jclass);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    createImageAssets
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_gltest_GLInterface_createImageAssets
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    createImage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_gltest_GLInterface_createImage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    createAnimationAssets
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_gltest_GLInterface_createAnimationAssets
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    createAnimation
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_gltest_GLInterface_createAnimation
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    drawImage
 * Signature: (IIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_example_gltest_GLInterface_drawImage
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    playAnimation
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_example_gltest_GLInterface_playAnimation
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    openAlpha
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_gltest_GLInterface_openAlpha
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    closeAlpha
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_gltest_GLInterface_closeAlpha
  (JNIEnv *, jclass);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    createBuffer
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_gltest_GLInterface_createBuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    drawBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_gltest_GLInterface_drawBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    endDrawBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_gltest_GLInterface_endDrawBuffer
  (JNIEnv *, jclass);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    renderBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_gltest_GLInterface_renderBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_gltest_GLInterface
 * Method:    setApkSource
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_gltest_GLInterface_setApkSource
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
